name: Shipment CI Pipeline

on:
  push:
    branches: [ master ]

env:
  java-distribution: 'temurin'
  java-version: '17'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.java-distribution }}
          java-version: ${{ env.java-version }}

      - name: Build Project
        run: mvn clean install -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.java-distribution }}
          java-version: ${{ env.java-version}}

      - name: Run Tests
        run: mvn test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/